### ISSUE TITLE
Issue with theme library causing test failures

### ISSUE THREAD

**Issue by rychomis** [microsoft/fluentui-react-native#1004]
### Environment Information

- **Package version(s)**:
```
    "@fluentui-react-native/apple-theme": "^0.7.23",
    "@fluentui-react-native/default-theme": "^0.8.3",
    "@fluentui-react-native/theme": "^0.5.19",
    "@fluentui-react-native/theme-types": "^0.12.1",
    "@fluentui-react-native/win32-theme": "^0.13.2",
    "@fluentui/react-native": "0.25.13",
```

- **Platform**:
all

### Please provide a reproduction of the bug:

when running a test 

```
    const theme = createDefaultTheme();

    const tree = renderer
      .create(
        <ThemeProvider theme={theme}>
          <Component>
        </ThemeProvider>,
      )
      .toJSON();
    expect(tree).toMatchSnapshot();
```

I get this error

```
    Unhandled discriminated union member: undefined

      at Object.assertNever (../../common/temp/node_modules/.pnpm/assert-never@1.2.1/node_modules/assert-never/index.js:32:11)
      at ../../common/temp/node_modules/.pnpm/@fluentui-react-native/default-theme@0.8.3_d1c53b50ef9cfe887d69c9bf99b2b704/node_modules/@fluentui-react-native/default-theme/src/createDefaultTheme.ts:19:20
      at ThemeReference.get [as theme] (../../common/temp/node_modules/.pnpm/@fluentui-react-native/theme@0.5.19_e6f6aee82b874cf5b3bad5d449c8dc73/node_modules/@fluentui-react-native/theme/src/themeReference.ts:61:66)
      at ../../common/temp/node_modules/.pnpm/@fluentui-react-native/theme@0.5.19_e6f6aee82b874cf5b3bad5d449c8dc73/node_modules/@fluentui-react-native/theme/src/ThemeProvider.tsx:14:9
      at mountState (../../common/temp/node_modules/.pnpm/react-test-renderer@16.13.1_react@16.13.1/node_modules/react-test-renderer/cjs/react-test-renderer.development.js:5971:20)
      at Object.useState (../../common/temp/node_modules/.pnpm/react-test-renderer@16.13.1_react@16.13.1/node_modules/react-test-renderer/cjs/react-test-renderer.development.js:6516:16)
      at Object.useState (../../common/temp/node_modules/.pnpm/react@16.13.1/node_modules/react/cjs/react.development.js:1497:21)
      at Object.<anonymous>.exports.ThemeProvider (../../common/temp/node_modules/.pnpm/@fluentui-react-native/theme@0.5.19_e6f6aee82b874cf5b3bad5d449c8dc73/node_modules/@fluentui-react-native/theme/src/ThemeProvider.tsx:14:9)
      at renderWithHooks (../../common/temp/node_modules/.pnpm/react-test-renderer@16.13.1_react@16.13.1/node_modules/react-test-renderer/cjs/react-test-renderer.development.js:5552:18)
      at mountIndeterminateComponent (../../common/temp/node_modules/.pnpm/react-test-renderer@16.13.1_react@16.13.1/node_modules/react-test-renderer/cjs/react-test-renderer.development.js:7918:13)

```

### Hypothesis
I think this might be some weird interaction of passing a partial theme to the theme provider,

### Priorities and help requested:

Are you willing to submit a PR to fix? No

Requested priority: Blocking

Products/applications affected: (if applicable)
Excel Taskpane

**Comment by Saadnajmi** [comment]
Tagging @rurikoaraki , looks like @rychomis  hit an assertNever

**Comment by Saadnajmi** [comment]
It looks like we need to pass an appearance into createDefaultTheme? https://github.com/microsoft/fluentui-react-native/blob/4628684e9b1b337af67c5d0a1833ad8646db170a/packages/theming/default-theme/src/createDefaultTheme.ts

**Comment by rurikoaraki** [comment]
Hmm the " || light" should've taken care of that, but I guess it's causing an issue. I'll take a look.

**Comment by rurikoaraki** [comment]
@rychomis PR is out to fix now.

By the way, the default theme will not give you the correct win32 colors, just so you're aware. If you want to use colors from a particular palette and have it respond to Office theme, you should use createOfficeTheme (see https://github.com/microsoft/fluentui-react-native/blob/master/docs/pages/Theming/DefaultThemes.md#integration-with-office)

**Comment by rychomis** [comment]
@rurikoaraki I'm testing the default and the createOfficeTheme
